### PR TITLE
Added Terraform on AWS video tutorial

### PR DESCRIPTION
**Pull request by Nobulali**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
1. Added a video about Terraform on AWS

## Purpose
There are no terraform videos yet

### CODE REVIEW

**Review by NicAtak — APPROVED** [review]
Thanks for the helpful link Nobu! The Markdown makes it easy to read. :)

**Review by NicAtak — APPROVED** [review]
Love this! Thanks for the tunes! :)

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
This is a great contribution! Thanks @Nobulali ! 

The only thing that is making this a blocker is the merge conflict. We didnt go over merge conflicts yet, so this is a great place for a micro-talk! Ill be slacking you if you don't mind to set something up. Please take a look at: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Review by michaelachrisco — APPROVED** [review]
Awesome @Nobulali Looks good! Thanks for taking a look at the merge conflict and resolving it! Links look great. Approved!

**Comment by michaelachrisco** [comment]
@Nobulali I think you are good for merging! Feel free to press that merge button when you are ready. Thanks again for contributing.

**Pull request merged**
