### PR TITLE
feat(README): add useful links

### PR DESCRIPTION
**Pull request by EricL94**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
1. Add useful links for Terraform link https://developer.hashicorp.com/terraform
2. Terraform video https://www.youtube.com/watch?v=YcJ9IeukJL8

## Purpose
Useful tools for Terraform

## Approach
To add links to the README.md

## Pre-Testing TODOs
To make sure the sure the links actually worked properly.

## Testing Steps
Visit the links beforehand. 

## Learning
Learned how to add links to README.md

### CODE REVIEW

**Review by demewozshiferaw — DISMISSED** [review]
Hi Eric . I notice there is a merge conflict on your pull request .
thank you for the resource.

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
Hello @EricL94 ! 

Nice job on your first pull request. I like the link and installing terraform is indeed one of the more important things we did early on in the apprenticeship. 

A couple of blockers: 
1. Please fill out your description on the PR. It helps your Reviewers understand what the changes are referring to and how you went about your solution.
2. We didnt go over merge conflicts yet, so please take a look at: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github If you have any trouble, feel free to reach out via the slack channel. I think you will see others may have had the same issue. Merge conflicts must be resolved before GitHub will allow changed to be merged. 

Thanks for the contribution!

**Review by michaelachrisco — APPROVED** [review]
Awesome, thanks for dealing with the merge conflicts! Looks like everything is ready to go. 

One last recommendation, we may want to push the links to under the `## Contributing to this Repository` at some point. This is very much not a blocker, just a suggestion.

**Review by fedluk70 — COMMENTED** [review]
I just reviewed the link looks great

**Comment by michaelachrisco** [comment]
How do you feel about us going over how to deal with git commit conflicts? Here is a good tutorial if you would like to follow along: https://www.freecodecamp.org/news/resolve-merge-conflicts-in-git-a-practical-guide/

Alternatively you can click "Resolve conflicts" above and have Github attempt to fix it for you. Let me know what you think!

**Review by michaelachrisco — APPROVED** [review]
Thanks for dealing with the merge conflict! Looks good, approving. You can merge at any time.

**Comment by michaelachrisco** [comment]
Thanks @EricL94 for the contribution and @demewozshiferaw for the PR review!

**Pull request merged**
