### PR TITLE
a practical programming

### PR DESCRIPTION
**Pull request by tiruworktito**
## Changes
Added Command Line link to notes

## Purpose
updated the useful links and docs

## Approach
added more  links to the README.md

## Learning
practice pull request

Closes #6

### CODE REVIEW

**Review by Ruhama21 — COMMENTED** [review]
Thanks you for sharing the document.

**Comment by tiruworktito** [comment]
Updated pull request

**Review by fedluk70 — APPROVED** [review]
nice job Tiru

**Comment by michaelachrisco** [comment]
Awesome job looks good! 

Only blocker now is dealing with the git conflict. I would suggest using Githubs own "Resolve conflicts" button above to pull in the changes. It should allow you to merge afterwards.

**Pull request closed without merging**
