### PR TITLE
added hex to hsl

### PR DESCRIPTION
**Pull request by PairojSansri**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
_List Changes Introduced by this PR_
1. Item 1
2. Item 2

## Purpose
_Describe the problem or feature in addition to a link to the issues._

## Approach
_How does this change address the problem?_

## Pre-Testing TODOs
_What needs to be done before testing_
- [] Change database values in x collection to y.

## Testing Steps
_How do the users test this change?_

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #000

### CODE REVIEW

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
Hello @PairojSansri!

Links look great, they all resolve and I really like the inclusion of the link to the ssh keys in different operating systems. Thats one that we dont usually go over but is super important as we deal with more than just Linux. 

A couple of blockers: 
1. Please fill out your description on the PR. It helps your Reviewers understand what the changes are referring to and how you went about your solution. 
2. Please make sure to assign @michaelachrisco , @TheLady , and the @Shift3/devops-apprentices to the Pull Request.

Thanks again for contributing!

**Comment by michaelachrisco** [comment]
@PairojSansri Any luck here? Just let me know if you need any help with the above suggestions.

**Comment by michaelachrisco** [comment]
@PairojSansri  Let me know if you need any help here.

**Comment by PairojSansri** [comment]
I closed the request, thank you.

**Pull request closed without merging**
