### PR TITLE
Yo 6 add ca again

### PR DESCRIPTION
**Pull request by oyoona**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
_List Changes Introduced by this PR_
1. Added another CodeAcademy link

## Purpose
To provide a resource to others

## Approach
Added link to README.md

## Pre-Testing TODOs
Verify that links are functional

## Testing Steps
Navigate to link

## Learning
N/A

This is Yoona's 2nd pull request

Closes #6

### CODE REVIEW

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
Hello @oyoona ! Nice job on the PR! Looks great, some really good links. 


Only one Change Request:
Please make sure to assign @michaelachrisco , @TheLady , and the https://github.com/orgs/Shift3/teams/devops-apprentices to the Pull Request.

Thanks for the contribution.

**Review by Ruhama21 — COMMENTED** [review]
good and help full link "Coding is a team sport,

**Review by michaelachrisco — APPROVED** [review]
Awesome job, approved!

**Review by michaelachrisco — COMMENTED** [review]
Whats the .DS_Store file doing here? Im thinking this may need to be added to our gitignore file, as some people dont have Mac OS.

**Pull request merged**
