### PR TITLE
feat(README): add useful links

### PR DESCRIPTION
**Pull request by michaelachrisco**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
1. Added S&P repo link to notes

## Purpose
To take a closer look at our Standards and Practices

## Approach
Added the link to the README.md

## Pre-Testing TODOs
- [ ] Links are not 404ing

## Testing Steps
Make sure links go to right page

## Learning
None ATM

Closes #6

### CODE REVIEW

**Comment by michaelachrisco** [comment]
@Shift3/devops-apprentices hello everyone! If you get a chance, can you review my PR? No rush.

**Review by Ruhama21 — COMMENTED** [review]
_I review the pull request, the link works good._

**Review by NicAtak — APPROVED** [review]
Great resource, Thanks Michael!

**Comment by Nobulali** [comment]
Hi, thanks for the link. it's a good read!

**Review by fedluk70 — COMMENTED** [review]
I able to review the link and went through  well

**Comment by michaelachrisco** [comment]
Thanks everyone! 

Please don't merge other peoples Pull Requests. The individual (Assignee) that should be merging the Pull Request should be the one that submits it. I went over this in passing but I may not have gone over the specifics. 

Once you are done with reviewing the Pull Request and you see that its good, please click the "File Changed" -> click "Review Changes" -> click "Approve" with a message. If you have any questions, feel free to put those on slack and/or take a look at our training video.

**Pull request merged**
