### PR TITLE
feat(README): added terraform links

### LINKED ISSUE #4: [Feat]: Add useful terraform video resources
### Is your feature request related to a problem? Please describe.

We dont have any terraform video resources available for apprentices to take a look at. 

### Describe the solution you'd like.
We should add more terraform resources to our repo.

Please add a **link** with a **description** to the main README.md file. 

Example: 
* How to contribute to projects: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

### Describe alternatives you've considered

_No response_

### Additional context

This is both a sample and useful example regarding adding issues to the Github repo, contributing to a repo, and creating a Pull Request from a forked resource.

### PR DESCRIPTION
**Pull request by TheLady**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
1. Added terraform links shared in slack

## Purpose
To provide more info to apprentices regarding terraform. 

## Approach
Linking each of the resources provided in slack. 

## Pre-Testing TODOs
_What needs to be done before testing_
- [x] Verify the links go to youtube and go to the right pages. 

## Testing Steps
Click on the links and take a look at the material. 

## Learning
* GitHubs own documentation on the process: https://docs.github.com/en/get-started/quickstart
* Forking: https://docs.github.com/en/get-started/quickstart/fork-a-repo
* How to contribute to projects: https://docs.github.com/en/get-started/quickstart/contributing-to-projects
* Github markdown: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Closes #4

### CODE REVIEW

**Review by NicAtak — APPROVED** [review]
Thank you for adding the Terraform links. They all linked up with no problems and they will be a great help.

**Comment by NicAtak** [comment]
@michaelachrisco an after thought about the Terraform links: having them as inline links would make it easier and quicker to navigate to the external links. [Github Markdown Links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)

**Comment by Nobulali** [comment]
Thanks for the notes.

**Comment by Futsum1** [comment]
Thank you so much! for adding the link

**Comment by michaelachrisco** [comment]
Dang you all are quick! Ill be going over this in our meeting but thanks for the reviews.

**Comment by michaelachrisco** [comment]
> @michaelachrisco an after thought about the Terraform links: having them as inline links would make it easier and quicker to navigate to the external links. [Github Markdown Links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)

I think this is an excellent suggestion. Im thinking we should reference the GitHub Markdown link that you provided within the README for everyone else. What do you think?

**Comment by NicAtak** [comment]
I agree. I know you are already aware of the links and Markdown use in
Github, but I wanted to leave a comment that would be helpful for
everyone as a good practice. Most if not all are already familiar with
HTML, so it should be an easy transition.

**Review by michaelachrisco — APPROVED** [review]
Looks great, love the links. All of them resolve and looks like they were useful to the team!

**Review by Ruhama21 — APPROVED** [review]

**Review by anjuyeddu — COMMENTED** [review]
Great resource!

**Comment by Ruhama21** [comment]
Thank you for your support!

**Review by EricL94 — APPROVED** [review]
Looks great. Links look great as well.

**Pull request merged**
