### PR TITLE
Pls 6 fourthpr

### PR DESCRIPTION
**Pull request by PairojSansri**
**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes

1. added notes

## Purpose
to practice PR

## Approach
creates experience

## Pre-Testing TODOs
N/A

## Testing Steps
repetition

## Learning
how to do a PR

Closes #006

### CODE REVIEW

**Comment by Connie818** [comment]
Good resources, Pairoj.

**Comment by michaelachrisco** [comment]
@PairojSansri Please go ahead and include myself (@michaelachrisco ) and the @Shift3/devops-apprentices team to the list of reviewers in order to get this PR reviewed.

**Comment by PairojSansri** [comment]
@michaelachrisco Done, thank you.

**Review by anjuyeddu — COMMENTED** [review]
These are great info, Pairoj.

**Comment by michaelachrisco** [comment]
Closing all old Prs over 1 month old. Feel free to re-submit!

**Pull request closed without merging**
